import { chromium } from "@playwright/test";
const W = +process.argv[2] || 390, H = +process.argv[3] || 844, tag = process.argv[4] || "m";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 2 });
const errs = [];
p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
p.on("console", (m) => m.type() === "error" && errs.push("console: " + m.text()));
await p.goto("http://localhost:4173/?test=1");
await p.waitForTimeout(600);
await p.getByTestId("book").click();
await p.waitForTimeout(900);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s1a.png" });
await p.locator('[data-testid^="day-"]:not([aria-disabled="true"])').nth(3).click();
await p.waitForTimeout(700);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s1b.png" });
await p.getByTestId("next").click(); await p.waitForTimeout(800);
await p.locator('[data-testid^="slot-"]:not([disabled])').nth(17).click();
await p.waitForTimeout(700);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s2.png" });
await p.getByTestId("next").click(); await p.waitForTimeout(800);
await p.getByTestId("place-NAB").click(); await p.waitForTimeout(700);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s3.png" });
await p.getByTestId("next").click(); await p.waitForTimeout(800);
await p.getByTestId("reason-0").click(); await p.getByTestId("reason-3").click();
await p.getByTestId("note").fill("bring snacks");
await p.getByTestId("miss").fill("100");
await p.waitForTimeout(700);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s4.png" });
await p.getByTestId("next").click(); await p.waitForTimeout(800);
await p.getByTestId("next").click({ force: true }); await p.waitForTimeout(300);
console.log("toast:", await p.getByTestId("toast").textContent());
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-s5.png" });
await p.getByTestId("back").click(); await p.waitForTimeout(800);
console.log("after back:", await p.getByTestId("step-count").textContent(), await p.getByTestId("love-pct").textContent());
console.log(errs.join("\n") || "no errors");
await b.close();
