import { chromium } from "@playwright/test";
const W = +process.argv[2] || 390, H = +process.argv[3] || 844, tag = process.argv[4] || "m";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 2 });
const errs = [];
p.on("pageerror", (e) => errs.push("pageerror: " + e.message));
p.on("console", (m) => m.type() === "error" && errs.push("console: " + m.text()));
await p.goto("http://localhost:4173/?test=1");
await p.waitForTimeout(500);
const png = Buffer.from(await p.evaluate(() => { const c = document.createElement("canvas"); c.width = 600; c.height = 800; const x = c.getContext("2d"); const g = x.createLinearGradient(0,0,600,800); g.addColorStop(0,"#FF5FA2"); g.addColorStop(1,"#5B9BFF"); x.fillStyle = g; x.fillRect(0,0,600,800); x.fillStyle="#fff"; x.beginPath(); x.arc(300,330,150,0,7); x.fill(); x.fillStyle="#3A2A4D"; x.beginPath(); x.arc(250,310,18,0,7); x.arc(350,310,18,0,7); x.fill(); return c.toDataURL("image/png").split(",")[1]; }), "base64");
await p.getByTestId("book").click(); await p.waitForTimeout(700);
await p.locator('[data-testid^="day-"]:not([aria-disabled="true"])').nth(3).click();
await p.getByTestId("next").click(); await p.waitForTimeout(500);
await p.locator('[data-testid^="slot-"]:not([disabled])').nth(17).click();
await p.getByTestId("next").click(); await p.waitForTimeout(500);
await p.getByTestId("place-NAB").click();
await p.getByTestId("next").click(); await p.waitForTimeout(500);
await p.getByTestId("reason-0").click(); await p.getByTestId("reason-1").click();
await p.getByTestId("note").fill("bring snacks pls");
await p.getByTestId("next").click(); await p.waitForTimeout(500);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-pay0.png" });
await p.getByTestId("gallery-input").setInputFiles({ name: "me.png", mimeType: "image/png", buffer: png });
await p.waitForTimeout(900);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-pay1.png" });
await p.getByTestId("next").click(); await p.waitForTimeout(1200);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-review.png" });
await p.getByTestId("edit-place").click(); await p.waitForTimeout(600);
console.log("edit ->", await p.getByTestId("step-count").textContent(), await p.getByTestId("next").textContent());
await p.getByTestId("place-CV-BLOCK").click();
await p.getByTestId("next").click(); await p.waitForTimeout(900);
console.log("back on", await p.getByTestId("step-count").textContent(), (await p.getByTestId("ticket").textContent()).includes("CV BLOCK"));
await p.getByTestId("confirm").click(); await p.waitForTimeout(1500);
console.log("h1:", await p.locator("h1").first().textContent());
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-success.png" });
let d = p.waitForEvent("download"); await p.getByTestId("save").click(); let dl = await d;
await dl.saveAs("/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/pass.png"); console.log("png:", dl.suggestedFilename());
d = p.waitForEvent("download"); await p.getByTestId("calendar").click(); dl = await d;
await dl.saveAs("/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/appt.ics"); console.log("ics:", dl.suggestedFilename());
await p.getByTestId("again").click(); await p.waitForTimeout(900);
await p.getByTestId("history-count").click(); await p.waitForTimeout(700);
await p.screenshot({ path: "/private/tmp/claude-501/-Users-damaruk-dev-appointment/6a785ffa-cfe4-4b57-9240-789c46a83d82/scratchpad/" + tag + "-history.png" });
console.log(errs.join("\n") || "no errors");
await b.close();
